import type { Metadata } from "next";
import { openSans, robotoCondensed, inter } from '@/lib/fonts';
import "@/styles/globals.scss";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${robotoCondensed.variable} ${inter.variable}`}>

        <Header />

        {children}

        <Footer />

      </body>
    </html>
  );
}
