import type { Metadata } from "next";
import { openSans, robotoCondensed, inter } from '@/lib/fonts';
import "@/styles/globals.scss";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import { Locale } from "@/lib/locales";

export async function generateMetadata({
  params
}: {
  params: Promise<{ locale: Locale }>;
}): Promise<Metadata> {
  const { locale: _locale } = await params;
  return {
    title: "Create Next App",
    description: "Generated by create next app",
    alternates: {
      languages: {
        'ru': '/ru',
        'en': '/en',
        'uz': '/uz',
      },
    },
  };
}

export default async function LocalizedLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;
  return (
    <html lang={locale}>
      <body className={`${openSans.variable} ${robotoCondensed.variable} ${inter.variable}`}>

        <Header locale={locale} />

        {children}

        <Footer locale={locale} />

      </body>
    </html>
  );
}
